language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a
android:
  components:
  
    - plattform-tools
    - tools
  
    # BuildTools version
    - build-tools-19.1.0
    
    # SDK version used for compiling
    - android-19

    - sys-img-armeabi-v7a-android-19

# newer version of gradle
before_install:
  - wget http://services.gradle.org/distributions/gradle-1.12-bin.zip
  - unzip -qq gradle-1.12-bin.zip
  - export GRADLE_HOME=$PWD/gradle-1.12
  - export PATH=$GRADLE_HOME/bin:$PATH

# Create, Start and Wait
before_script:
  - mvn install:install-file -DgroupId=com.google.android.maps -DartifactId=maps -Dversion=18_r3 -Dpackaging=jar -Dfile="$ANDROID_HOME/add-ons/addon-google_apis-google-18/libs/maps.jar"
  - mvn install:install-file -DgroupId=com.android.support -DartifactId=support-v4 -Dversion=19.0.1 -Dpackaging=jar -Dfile="$ANDROID_HOME/extras/android/support/v4/android-support-v4.jar"
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  
script: 
  - cd Lighter
  - gradle build connectedCheck
  - mvn clean install